name = "DFT-RTM"
version = "0.1.0"
license = "license"
author = "Átila Saraiva Quintela Soares, Peterson Nogueira"
maintainer = "atilasaraiva@gmail.com"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[dependencies]
pyplot-fortran.git = "https://github.com/jacobwilliams/pyplot-fortran"
pyplot-fortran.tag = "3.2.0"

